version: "3.9"
services: 
    control:
        image: safe1/control
        pull_policy: never
        restart: unless-stopped
        env_file:
            - ./control/.env
        environment:
            - DATA_SERVICE_URL=http://data:8000
        ports: 
            - "8010:8010"
        depends_on:
            - data
    data:
        image: safe1/data
        pull_policy: never
        restart: unless-stopped
        environment:
            - PSQL_USERNAME=safe1admin
            - PSQL_PASSWORD=securepassword
            - PSQL_DB_NAME=safe1
            - PSQL_HOSTNAME=postgres
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    postgres:
        image: postgres
        pull_policy: if_not_present
        restart: unless-stopped
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=psql
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./data/initdb:/docker-entrypoint-initdb.d/
volumes: 
    pgdata: 
        external: true
